UrbanDjango/UrbanDjango/urls.py
from django.contrib import admin
from django.urls import path
from task2.views import Class_view, func_view
import task4.views
import task5.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('class/', Class_view.as_view()),
    path('func/', func_view),
    path('platform/', task4.views.platform_index),
    path('platform/games/', task4.views.catalog),
    path('platform/cart/', task4.views.cart),
    path('', task5.views.sign_up_by_html),
    path('django_sign_up', task5.views.sign_up_by_django),
]

UrbanDjango/example1/models.py
from django.db import models

# Create your models here.

UrbanDjango/example2/models.py
from django.db import models

# Create your models here.

UrbanDjango/example3/models.py
from django.db import models

# Create your models here.

UrbanDjango/task2/models.py
from django.db import models

# Create your models here.

UrbanDjango/task3/models.py
from django.db import models

# Create your models here.

UrbanDjango/task4/models.py
from django.db import models

# Create your models here.

UrbanDjango/task5/models.py
from django.db import models

# Create your models here.

UrbanDjango/task5/forms.py
from django import forms


class UserRegister(forms.Form):
    username = forms.CharField(max_length=30, label="Введите логин:")
    password = forms.CharField(widget=forms.PasswordInput, min_length=8,
                               label="Введите пароль:")
    repeat_password = forms.CharField(widget=forms.PasswordInput,
                                      min_length=8, label="Повторите пароль:")
    age = forms.IntegerField(min_value=1, max_value=200,
                             label="Введите свой возраст:")

UrbanDjango/example1/views.py
from django.shortcuts import render

# Create your views here.

UrbanDjango/example2/views.py
from django.shortcuts import render

# Create your views here.

UrbanDjango/example3/views.py
from django.shortcuts import render

# Create your views here.

UrbanDjango/task2/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.


class Class_view(TemplateView):
    template_name = 'second_task/class_template.html'


def func_view(request):
    return render(request, 'second_task/func_template.html')

UrbanDjango/task3/views.py
from django.shortcuts import render


def platform_index(request):
    return render(request, 'third_task/platform.html')


def catalog(request):
    return render(request, 'third_task/games.html',
                  {'games': ['Atomic Heart',
                             'Cyberpank 2077',
                             'PayDay 2']})


def cart(request):
    return render(request, 'third_task/cart.html')

UrbanDjango/task4/views.py
from django.shortcuts import render


def platform_index(request):
    return render(request, 'fourth_task/platform.html',
                  {'header': 'Главная страница'})


def catalog(request):
    return render(request, 'fourth_task/games.html',
                  {'header': 'Игры',
                   'games': ['Atomic Heart',
                             'Cyberpank 2077',
                             'PayDay 2']})


def cart(request):
    return render(request, 'fourth_task/cart.html', {'header': 'Корзина'})

UrbanDjango/task5/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import UserRegister

# Create your views here.

users = {'Василий': {'password': '12230823', 'age': 23},
         'Елена': {'password': 'qwerty123', 'age': 18},
         'Тимур': {'password': '1|Awv&8jRv', 'age': 19},
         'marina': {'password': '00112233', 'age': 27}}


def sign_up_by_html(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        repeat_password = request.POST.get('repeat_password')
        age = int(request.POST.get('age'))

        error = ''
        if password != repeat_password:
            error = 'Пароли не совпадают'
        elif age < 18:
            error = 'Вы должны быть старше 18'
        elif username in users:
            error = 'Пользователь уже существует'

        if error:
            return render(request, 'fifth_task/registration_page.html',
                          {'error': error, 'username': username, 'age': age})
        else:
            users[username] = {'password': password, 'age': age}
            return HttpResponse(f'Приветствуем, {username}!')

    return render(request, 'fifth_task/registration_page.html')


def sign_up_by_django(request):
    if request.method == 'POST':
        form = UserRegister(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            repeat_password = form.cleaned_data['repeat_password']
            age = form.cleaned_data['age']

            error = ''
            if password != repeat_password:
                error = 'Пароли не совпадают'
                form.fields['password'].widget.attrs.update(
                    {'autofocus': '', 'class': 'col_input'})
                form.fields['repeat_password'].widget.attrs.update(
                    {'class': 'col_input'})
            elif age < 18:
                error = 'Вы должны быть старше 18'
                form.fields['age'].widget.attrs.update(
                    {'autofocus': '', 'class': 'col_input'})
            elif username in users:
                error = 'Пользователь уже существует'
                form.fields['username'].widget.attrs.update(
                    {'autofocus': '', 'class': 'col_input'})

            if error:
                return render(request, 'fifth_task/registration_page.html',
                              {'error': error, 'form': form})
            else:
                users[username] = {'password': password, 'age': age}
                return HttpResponse(f'Приветствуем, {username}!')
    else:
        return render(request, 'fifth_task/registration_page.html',
                      {'form': UserRegister()})

UrbanDjango/templates/fifth_task/registration_page.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Имитация регистрации</title>
  <style>.col_input{background-color:#e8f0fe}</style>
</head>
<body>
<header>
  <h1>Имитация регистрации</h1>
  <h3>(через
  {% if request.resolver_match.route == '' %}
    HTML{% else %}Django{% endif %} форму)</h3>
  {% if error %}<h2 style="color: red">{{ error }}</h2>{% endif %}
</header>
<main>
  <form method="post">
    {% csrf_token %}
    {% if request.resolver_match.route == '' %}
      <p>
      <label for="id_username">Введите логин:</label>
      <input type="text" id="id_username" name="username" maxlength="30"
        {% if username %}value="{{ username }}"{% endif %}
        {% if error == 'Пользователь уже существует' %}
        autofocus class="col_input"
        {% endif %}
        required>
      </p>
      <p>
      <label for="id_password">Введите пароль:</label>
      <input type="password" id="id_password" name="password" minlength="8"
        {% if error == 'Пароли не совпадают' %}
        autofocus class="col_input"
        {% endif %}
        required>
      </p>
      <p>
      <label for="id_repeat_password">Повторите пароль:</label>
      <input type="password" id="id_repeat_password" name="repeat_password"
        {% if error == 'Пароли не совпадают' %}class="col_input"{% endif %}
        minlength="8" required>
      </p>
      <p>
      <label for="id_age">Введите свой возраст:</label>
      <input type="number" id="id_age" name="age" min="1" max="200"
        {% if age %}value="{{ age }}"{% endif %}
        {% if error == 'Вы должны быть старше 18' %}
        autofocus class="col_input"
        {% endif %}
        required>
      </p>
    {% else %}
      {{ form.as_p }}
    {% endif %}
    <p><button type="submit">Зарегистрироваться</button></p>
  </form>
</main>
</body>
</html>

UrbanDjango/templates/fourth_task/cart.html
{% extends "fourth_task/menu.html" %}
{% block title %}Корзина{% endblock %}
{% block content %}
  <h1>Извините, ваша корзина пуста</h1>
  <p>но вы всегда можете выбрать из нашего
    <a href="/platform/games/">каталога</a> интересные игры</p>
{% endblock %}

UrbanDjango/templates/fourth_task/games.html
{% extends "fourth_task/menu.html" %}
{% block title %}Каталог игр{% endblock %}
{% block content %}
  <ul>
  {% for game in games %}
    <li>{{ game }} <button>Купить</button></li>
  {% endfor %}
  </ul>
{% endblock %}

UrbanDjango/templates/fourth_task/menu.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Интернет-магазин игр{% endblock %}</title>
</head>
<body>
<header>
  {% block pagename %}
  <h1>{{ header }}</h1>
  {% endblock %}
</header>
<nav>
  {% block menu %}
  <p><a href="/platform/">Главная</a></p>
  <p><a href="/platform/games/">Магазин</a></p>
  <p><a href="/platform/cart/">Корзина</a></p>
  {% endblock %}
</nav>
<main>
  {% block content %}{% endblock %}
</main>
<footer>
  {% block footer %}
  <p><a href=".."><button>Вернуться обратно</button></a></p>
  {% endblock %}
</footer>
</body>
</html>

UrbanDjango/templates/fourth_task/platform.html
{% extends "fourth_task/menu.html" %}
{% block footer %}{% endblock %}

UrbanDjango/templates/second_task/class_template.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Шаблон для классового представления</title>
</head>
<body>
  Это шаблон для классового представления
</body>
</html>

UrbanDjango/templates/second_task/func_template.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Шаблон для функционального представления</title>
</head>
<body>
  Это шаблон для функционального представления
</body>
</html>

UrbanDjango/templates/third_task/cart.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Корзина</title>
</head>
<body>
  <h1>Извините, ваша корзина пуста</h1>
  <p>но вы всегда можете выбрать из нашего
    <a href="/platform/games/">каталога</a> интересные игры</p>
  <p><a href=".."><button>Вернуться обратно</button></a></p>
</body>
</html>

UrbanDjango/templates/third_task/games.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Каталог игр</title>
</head>
<body>
  <h1>Игры</h1>
  <ul>
  {% for game in games %}
    <li>{{ game }} <button>Купить</button></li>
  {% endfor %}
  </ul>
  <p><a href=".."><button>Вернуться обратно</button></a></p>
</body>
</html>

UrbanDjango/templates/third_task/platform.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Интернет-магазин игр</title>
</head>
<body>
  <h1>Главная страница</h1>
  <p><a href="/platform/">Главная</a></p>
  <p><a href="/platform/games/">Магазин</a></p>
  <p><a href="/platform/cart/">Корзина</a></p>
</body>
</html>